import type { Metadata } from "next";
import { Roboto } from "next/font/google"; // Use Roboto instead of Inter
import "./globals.css";
import { NavBar } from "@/components/navbar";
import { ThemeProvider } from "./_provider";



const roboto = Roboto({ subsets: ["latin"], weight: ['400', '500', '700'] }); // Configure font weights

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} px-8 py-4`}> {/* Apply Roboto font and padding globally */}
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
